build: false

environment:
    PYTHON_HOME: "C:\\Python37"

    CONAN_USERNAME: "_"
    CONAN_LOGIN_USERNAME: "annulen"
    CONAN_CHANNEL: "_"
    CONAN_UPLOAD: "https://api.bintray.com/conan/qtproject/conan"
    CONAN_REMOTES: "https://api.bintray.com/conan/qtproject/conan"
    CONAN_OPTIONS: "*:shared=True,brotli:shared=True"

    matrix:
        - MINGW_CONFIGURATIONS: '7@x86@dwarf2@posix'
          CONAN_BUILD_REQUIRES: 'msys2_installer/latest@bincrafters/stable'
          CONAN_BUILD_TYPES: Release
        - MINGW_CONFIGURATIONS: '7@x86_64@seh@posix'
          CONAN_BUILD_REQUIRES: 'msys2_installer/latest@bincrafters/stable'
          CONAN_BUILD_TYPES: Release

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install --upgrade conan==1.22.0 conan_package_tools==0.31.0 bincrafters_package_tools==0.21.0
  - conan user # It creates the conan data directory

test_script:
  - python build.py
